### ISSUE TITLE
MAKE.EXE hangs on circle target

### ISSUE THREAD

**Issue by bttrx** [DosWorld/smallmake#2]
Hi!

Put this to `MAKEFILE` and run `MAKE.EXE`.

```
all: all
```

Make will run forever now.

Cheers,
Robert

**Comment by DosWorld** [comment]
Thanks, Robert!

Looks like a "make-bomb" :-)) (near to "mail-bomb" into Fidonet)
I'll fix it. (or, if require to much resources, provide way how to see and stop this madness)

PS: This is just a brainless toy-tool for >= 386 PC (and can be a great possibility for dinosaurs)

**Comment by DosWorld** [comment]
Fix is ready. I'll play with this version in my local env (i want see possible side-effects, i think one week) and then - push it to git.
